#!/bin/bash -eu

if ! type brew >/dev/null 2>/dev/null; then
  echo | /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
fi

if [[ "$(uname)" == "Darwin" ]]; then
  # Install from `Brewfile` generated by `brew bundle dump`
  brew bundle
fi
