#!/bin/bash -eu

if [[ $# -ne 1 ]]; then
  echo >&2 "Usage: $0 github-username"
  exit 1
fi
username="$1"
remote="$(git remote show origin -n | grep 'Fetch URL: ' | awk '{print $3}')"
prefix="${remote%%:*}"
suffix="${remote##*/}"

git remote add "${username}" "${prefix}:${username}/${suffix}"
