#!/bin/bash -eu

if [[ $# != 1 ]]; then
  echo >&2 "usage: $0 size"
  exit 1
fi
size="$1"

base="${size:0:$((${#size} - 1))}"
case "${size: -1}" in
  M)
    sectors=$((${base} * 1024 * 1024 / 512))
    ;;
  G)
    sectors=$((${base} * 1024 * 1024 * 1024 / 512))
    ;;
  *)
    echo >&2 "Unrecognised units; expect e.g. 1M or 1G"
    exit 2
esac

dev="$(hdiutil attach -nomount "ram://${sectors}")"
diskutil erasevolume HFS+ tmpfs ${dev}
