#!/bin/bash -eu

if [[ $# -eq 0 || $# -gt 2 ]]; then
  echo >&2 "Usage: $0 src [dst-basename]"
  exit 1
fi

src="$1"
if [[ $# -eq 2 ]]; then
  dst="$2"
else
  dst="$(basename "${src}")"
fi
hostname=reich.illicitonion.com

date="$(date +"%Y%m%d")"
dir="/dump/${date}"

ssh daw63@${hostname} mkdir -p "${dir}"
ssh daw63@${hostname} chmod 755 "${dir}"
scp "${src}" daw63@${hostname}:"\"${dir}/${dst}\""
ssh daw63@${hostname} chmod 644 \""${dir}/${dst}"\"

echo "http://${hostname}${dir}/${dst}"
