#!/bin/bash -eu

if [[ $# -eq 0 || $# -gt 2 ]]; then
  echo >&2 "Usage: $0 src [dst-basename]"
  exit 1
fi

src="$1"
if [[ $# -eq 2 ]]; then
  dst="$2"
else
  dst="$(basename "${src}")"
fi
hostname=reich.illicitonion.com
username=daw63

date="$(date +"%Y%m%d")"
dir="/var/www/reich.illicitonion.com/dump/${date}"

ssh ${username}@${hostname} mkdir -p -m 0755 "${dir}"
scp "${src}" "${username}@${hostname}:\"${dir}/${dst}\""
ssh "${username}@${hostname}" chmod 0644 \""${dir}/${dst}"\"

echo "http://${hostname}${dir}/${dst}"
